version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=8000
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: todoapp_dev