apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: log-output:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: PINGPONG_URL
              value: "http://ping-pong-svc:2345"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: message

          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt