apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todoapp
          image: todoapp:latest
          imagePullPolicy: Never
          volumeMounts: # Mount volume
            - name: images
              mountPath: /usr/src/app/images
          env:
            - name: PORT
              value: "3000"
